#!/usr/bin/env bash
# git-workflow.sh — NanoClaw Git automation (SSH mode)
# Usage:
#   git-workflow.sh init   "commit message"           → initial push to main
#   git-workflow.sh change "commit message" [branch]  → new branch + PR
#
# Requirements:
#   - SSH key added to GitHub (ssh -T git@github.com should say "Hi <user>!")
#   - gh CLI installed and authed (gh auth login --git-protocol ssh)
#   - git configured: git config --global user.name / user.email

set -euo pipefail

COMMAND="${1:-}"
COMMIT_MSG="${2:-"chore: auto-commit by nanoclaw"}"
BRANCH_NAME="${3:-}"

# ── helpers ──────────────────────────────────────────────────────────────────

log()  { echo "[git-workflow] $*"; }
die()  { echo "[git-workflow] ERROR: $*" >&2; exit 1; }

require_cmd() { command -v "$1" &>/dev/null || die "'$1' not found. Install it first."; }
require_cmd git
require_cmd gh

# Confirm GitHub connectivity — prefer SSH, fall back to HTTPS (NanoClaw proxy)
ssh_check() {
  local ssh_result
  ssh_result=$(ssh -T git@github.com 2>&1 || true)
  if [[ "$ssh_result" == *"Hi "* ]]; then
    log "SSH connectivity verified."
    return 0
  fi

  # SSH blocked — verify HTTPS via gh CLI (NanoClaw proxy injects auth)
  local gh_user
  gh_user=$(gh api user --jq '.login' 2>/dev/null || true)
  if [[ -n "$gh_user" ]]; then
    log "SSH unavailable; using HTTPS via NanoClaw proxy (user: $gh_user)."
    return 0
  fi

  die "Neither SSH nor HTTPS GitHub auth is available.
SSH output: $ssh_result
Run: gh auth login"
}

# Ensure we are inside a git repo
git rev-parse --git-dir &>/dev/null || die "Not inside a git repository."

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

# ── init: first push to main ─────────────────────────────────────────────────

cmd_init() {
  ssh_check
  log "Initialising repository and pushing to GitHub via SSH..."

  # Stage everything if nothing is staged
  if git diff --cached --quiet; then
    git add -A
  fi
  git diff --cached --quiet && die "Nothing to commit."

  # Get GitHub username from gh CLI
  GH_USER=$(gh api user --jq '.login')
  REPO_NAME=$(basename "$REPO_ROOT")

  git commit -m "$COMMIT_MSG"

  # Create GitHub repo if it doesn't already exist
  if gh repo view "${GH_USER}/${REPO_NAME}" &>/dev/null 2>&1; then
    log "GitHub repo already exists: ${GH_USER}/${REPO_NAME}"
  else
    log "Creating public GitHub repo: ${GH_USER}/${REPO_NAME}"
    gh repo create "$REPO_NAME" --public
  fi

  # Always set/overwrite the remote using SSH URL
  SSH_REMOTE="git@github.com:${GH_USER}/${REPO_NAME}.git"
  if git remote get-url origin &>/dev/null 2>&1; then
    git remote set-url origin "$SSH_REMOTE"
    log "Updated remote origin → $SSH_REMOTE"
  else
    git remote add origin "$SSH_REMOTE"
    log "Added remote origin → $SSH_REMOTE"
  fi

  CURRENT_BRANCH=$(git branch --show-current)
  git push -u origin "$CURRENT_BRANCH"

  log "✓ Initial push complete → ${SSH_REMOTE}"
}

# ── change: branch + PR ───────────────────────────────────────────────────────

cmd_change() {
  ssh_check

  # Auto-generate branch name from commit message if not supplied
  if [[ -z "$BRANCH_NAME" ]]; then
    BRANCH_NAME=$(echo "$COMMIT_MSG" \
      | tr '[:upper:]' '[:lower:]' \
      | sed 's/[^a-z0-9 ]//g' \
      | tr ' ' '-' \
      | cut -c1-50)
    BRANCH_NAME="nanoclaw/${BRANCH_NAME}-$(date +%s)"
  fi

  log "Creating branch: $BRANCH_NAME"
  git checkout -b "$BRANCH_NAME"

  # Stage everything if nothing is staged
  if git diff --cached --quiet; then
    git add -A
  fi
  git diff --cached --quiet && die "Nothing to commit on branch $BRANCH_NAME."

  git commit -m "$COMMIT_MSG"

  log "Pushing branch via SSH..."
  git push -u origin "$BRANCH_NAME"

  log "Opening pull request..."
  PR_URL=$(gh pr create \
    --title "$COMMIT_MSG" \
    --body "Automated PR created by NanoClaw agent.

## Changes
$(git diff origin/main...HEAD --stat 2>/dev/null || git log origin/main..HEAD --oneline 2>/dev/null || echo 'See commits above.')

---
*Generated by \`git-workflow.sh\` on $(date)*" \
    --base main)

  log "✓ PR created: $PR_URL"
}

# ── dispatch ──────────────────────────────────────────────────────────────────

case "$COMMAND" in
  init)   cmd_init ;;
  change) cmd_change ;;
  *) die "Unknown command '$COMMAND'. Use: init | change" ;;
esac
